### ISSUE TITLE
Import mechanism

### ISSUE THREAD

**Issue by maku** [se-panfilov/jsvat#19]
Wouldn't it be good idea to provide a kind of import mechanism for countries.
So you would be able to be more dynamic and to get only the necessarily code downloaded to the client (browser).

**Comment by se-panfilov** [comment]
@maku You're right, it's not really hard to implement, but... but let me say honestly - it's a library with a very few stars, and tbh I don't want to spend too much time working on it. Maybe later I'll implement that, but I cannot promise ))

**Comment by se-panfilov** [comment]
This feature will be added in v2.0.0
