### ISSUE TITLE
Swedish VAT numbers do not validate correctly

### ISSUE THREAD

**Issue by artur-gajewski** [se-panfilov/jsvat#20]
When validating Swedish VAT numbers, the result is always false with real-world VAT numbers, such as:

556012-5790
969728-1989
716453-0326

I have tried both SE and SV as country code and both return false.

**Comment by M-arcus** [comment]
@artur-gajewski You need to add 01 to them
`jsvat.checkVAT('SE556012579001');`
`jsvat.checkVAT('SE969728198901');`
`jsvat.checkVAT('SE716453032601');

**Comment by M-arcus** [comment]
I got the tip with 01 from here: https://www.momsens.se/check-vat-number

**Comment by se-panfilov** [comment]
Yes, that's right.

The actual regex for Swedish VATs is  `/^(SE)(\d{10}01)$/`.

I don't think that I should make `01` optional, so perhaps I'll keep this  check as is.
I only add some not into the readme

@M-arcus  Thanks a lot for you contributions ))
