### ISSUE TITLE
Allow for VIES lookup

### ISSUE THREAD

**Issue by pellejacobs** [se-panfilov/jsvat#22]
Would you consider functionality / accept a PR to implement a VIES lookup? The EU offers a GUI (http://ec.europa.eu/taxation_customs/vies) and an API endpoint.

**Comment by se-panfilov** [comment]
@pellejacobs Tbh I don't really know what "VIES lookup" means. I want this library to make no ajax calls to third-party endpoints

**Comment by pellejacobs** [comment]
The VIES is an additional check for validity of VAT numbers. But of course that is not possible if you do not want this library to make external requests. 

Thank you for your reply!
