### ISSUE TITLE
Why Estonia isn't supported?

### ISSUE THREAD

**Issue by valjar** [se-panfilov/jsvat#26]
Hi! 
I wonder why Estonia isn't supported in VAT validation checker? 
Or do you maybe have a typo in List of supported Countries? 
Because there is one country listed as Europe but Estonia is missing?

<img width="983" alt="screen shot 2018-04-01 at 13 42 15" src="https://user-images.githubusercontent.com/8543041/38172783-a841ede2-35b2-11e8-99c4-60f48fcb70c4.png">

Thank you for this library! ;)

**Comment by se-panfilov** [comment]
@valjar Hi, this is a mistake, Estonia is supported. I'll update the list ))

Thanks for your attention))
