### ISSUE TITLE
CZ: Individuals type 2

### ISSUE THREAD

**Issue by Steefanieee** [se-panfilov/jsvat#32]
Hi,

When I use this library to validate the Czech VAT number "CZ699000899", is returns false, yet when I use the site of VIES (http://ec.europa.eu/taxation_customs/vies/) it says that the VAT number is valid.
Maybe the validation rules changed of perhaps there is an error in the validation? According to the code this should be a Czech Individuals type 2 number.

Kind regards

**Comment by se-panfilov** [comment]
@Steefanieee Hm, that might happen. If you would know any info about that change -please let me know. I'll try to check it

**Comment by ofavre** [comment]
I found another library, sharing the same name, that implements this check properly: https://www.braemoor.co.uk/software/vat.shtml

**Comment by janb87** [comment]
This gist also contains a fix for it:

https://gist.github.com/svschannak/e79892f4fbc56df15bdb5496d0e67b85
