### ISSUE TITLE
Possibility to differentiate between invalid VAT and unsupported country?

### ISSUE THREAD

**Issue by jaanttil** [se-panfilov/jsvat#44]
Is there a possibility to know if VAT validation for specific country is supported?

We have a use case where customer submits WEB form with his name, address and VAT number etc and we should be able to validate at minimum EU VAT numbers. 

Now this library works great as long as the customer is from supported countries.

If the customer is for example from Canada or India and enters their local VAT Id, response is similar as it would be for invalid VAT.

Yes I could build hard-coded list of country ISO codes and then validate VAT only for the supported ones but it would be more future proof if I could get the list of supported country ISO codes from lib or if validation response could somehow differentiate between unsupported country / invalid VAT?

**Comment by belgac** [comment]
You can get the list of ISO codes from the lib by taking always the first argument of the codes array on countries (wich is the  ISO 3166-1 alpha-2 (2 letters) country code) apart from greece who uses the ISO 639-1 language code (EL) that you need to do by hand (see https://www.wikiwand.com/en/VAT_identification_number)

**Comment by belgac** [comment]
example

**Comment by se-panfilov** [comment]
this will be possible soon. In 2.3.0 via `isSupportedCountry` field of the result
