### ISSUE TITLE
generate example number for country

### ISSUE THREAD

**Issue by mathroc** [se-panfilov/jsvat#67]
For input placeholders I'd like to be able to generate a fake vat number from a country, the number should probably only look like a vat number for this country but not be a valid one

one example of each is enough, they don't have to be randomly generated (in fact event better if there's only one by country because it would be distracting if the number changed on page refresh)

**Comment by se-panfilov** [comment]
Hi @mathroc 

Honestly, that's far beyond of the scope of this library. 

I won't do that, and here I will describe why:

- Maybe I could provide hardcoded example for each country, but... some countries might have several different regex patterns, so it's not such clear which on to use;
- I check it in two steps - Regex + math. Even if you would generate string based on regex, what you would do with math? For existed functionality it will be an [inverse problem](https://en.wikipedia.org/wiki/Inverse_problem).
- The size of the lib will be much bigger.

So, I'd say it would be a good idea to write another library which can do that, but... Honestly I don't think that this functionality is heavy required, and perhaps some solutions are already here
