### ISSUE TITLE
node example

### ISSUE THREAD

**Issue by familiadalousa** [se-panfilov/jsvat#75]
Hello,

I just made npm i jsvat but i am unable to use it in node. How can it be done? With require givens error with your example using import also gives an error. Am using node 12.3.1. With the import command ives error in the first {. With the require complains about the main reference. Thank you

**Comment by se-panfilov** [comment]
@familiadalousa Hi, I think it was due to error in `package.json`. Fixed in `2.0.1` please update and try again.

Let me know in case of troubles.

**Comment by familiadalousa** [comment]
Hello, remain the error:
import {checkVAT, belgium} from 'jsvat'; 
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/servidor_html/fneon.eu/s/servidor.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
error: Forever detected script exited with code: 1

**Comment by se-panfilov** [comment]
@familiadalousa This happens (as I understand) because your nodejs env doesn't understand es6 import/exports.
You can do following things:
1. Execute you node scripts with babel ([link](https://timonweb.com/posts/how-to-enable-es6-imports-in-nodejs/));
2. Start node with flags to enabled es6 modules support (I don't really remember names of the flags);
3. Wait for the new release: I gonna provide `CommonJS` build for nodejs in a couple of days

**Comment by familiadalousa** [comment]
Hello, i will wait for option 3. I will provide feedback once it is available. Thank you.

**Comment by se-panfilov** [comment]
@familiadalousa You can try now with `2.1.0`

Should work like this:

```javascript
const { checkVAT, belgium, austria } = require('jsvat');
// const { checkVAT, belgium, austria } = require('jsvat/lib/commonjs'); // this is also possible - force to use nodejs' modules system

const a = checkVAT('BE0411905847', [belgium]); // true: accept only Belgium VATs
const b = checkVAT('BE0411905847', [belgium, austria]); // true: accept only Belgium or Austria VATs
const c = checkVAT('BE0411905847', [austria]); // false: accept only Austria VATs

console.info(a)
console.info(b)
console.info(c)
```

Please let me know if it doesn't solve your issue

**Comment by familiadalousa** [comment]
Hello,
Yes, now it works.  Problem solve. Thank you.

**Comment by se-panfilov** [comment]
@familiadalousa Always welcome, thank you for the report ))
