### ISSUE TITLE
Can't find variable: BigInt on Safari

### ISSUE THREAD

**Issue by ruinyourfun** [se-panfilov/jsvat#94]
![Screenshot 2020-04-09 at 11 44 27](https://user-images.githubusercontent.com/869988/78881728-7f9d9a80-7a57-11ea-900d-3bad44e70a09.png)

https://caniuse.com/#feat=bigint
Workaround: This [library](https://github.com/peterolson/BigInteger.js) works as a polyfill. Or [JSBI](https://github.com/GoogleChromeLabs/jsbi), which is a pure-JavaScript implementation of the official ECMAScript BigInt proposal (BTW, why not simple user `Number`?)

**Comment by wilgert** [comment]
@ruinyourfun 
Are you willing/able/available to create a PR. I'd be happy to review and merge it!

**Comment by ruinyourfun** [comment]
Well I could but to be honest I don't quite catch why the use of `BigInt` instead of `Number` (I doubt the tested value should ever be larger than 2^53)

Then the only change should be in `./src/lib/countries/netherlands.ts` l.59
`return Number(value) % Number(97) === Number(1);`

**Comment by MattivdWeem** [comment]
That was my pr that implemented the BigInt; i created a new one where i implemented jsbi; we can't use Number, due to the way that the check value is created in the format, which will almost always run above 2^53. (you can reproduce that by changing the % test into Number and run the test suite)
